### ISSUE TITLE
关于go调用并发时出现goroutine leak

### ISSUE THREAD

**Issue by l3m0n** [opensec-cn/kunpeng#34]
问题有点类似: https://github.com/docker/distribution/issues/473

出现在net/http.(*persistConn).writeLoop，并发数量大概1000，但是出现了goroutine 2w+...

![9A9133F260DEDEFE5F33D6803D13B956](https://user-images.githubusercontent.com/10672574/57361265-a6e84980-71ae-11e9-84bb-91f8c45f8e50.jpg)

问题以及得到解决:
/github.com/opensec-cn/kunpeng/util/net.go

使用**DisableKeepAlives: true**关闭一下

```
transport := &http.Transport{
		TLSClientConfig:   &tls.Config{InsecureSkipVerify: true},
		DisableKeepAlives: true,
	}
```

注意的是每次都会调用setProxy, 里面的逻辑会翻盖init()设置的`client.Transport`

```
func RequestDo(request *http.Request, hasRaw bool) (Resp, error) {
	setProxy()
}
```

**Comment by ywolf** [comment]
收到 晚会我测试一下
