### ISSUE TITLE
如果要使用elasticsearch_unauth.json进行es未授权访问该怎么传参？

### ISSUE THREAD

**Issue by Ozipin** [opensec-cn/kunpeng#46]

**Comment by ywolf** [comment]
{
"type": "service",
"netloc": "10.11.11.111:9999",
"target": "elasticsearch"
}

**Comment by Ozipin** [comment]
> {
> “ type”：“服务”，
> “ netloc”：“ 10.11.11.111:9999”，
> “ target”：“ elasticsearch”
> }

3q
