### ISSUE TITLE
kunpeng/plugin/json/discuz_misc_sqli.json  path参数格式不对

### ISSUE THREAD

**Issue by qhxb** [opensec-cn/kunpeng#53]
discuz_misc_sqli.json
![image](https://user-images.githubusercontent.com/22363218/78751420-c7afb500-79a4-11ea-9456-055decaac1ab.png)
其他path都是/开头，运行时效果如下
![image](https://user-images.githubusercontent.com/22363218/78751504-f463cc80-79a4-11ea-8ddf-ffb83348e11c.png)

**Comment by ywolf** [comment]
感谢反馈
